### PR TITLE
feat: Extending AWS Preset wildcards and checks.

### PR DESCRIPTION
**Pull request by GuillaumeRochat**
I will try to add support for the `L`, `W` and `#` wildcards for the day of week and day of month for the AWS Preset. For each, I will add a config flag like done with all other checks.

I also read the Schedule Expressions documentation once more and noticed that the rule regarding the blank day basically means that there must always be at least one blank for AWS schedule expression, so I added a check to ensure we at least have one `?` in the cron.

What do you think of those flag names?

- `useLastDay` for the `L`.
- `useWeekDay` for the `W`.
- `useWeekNumber` for the `#`.
- `mustHaveBlankDayField` for the fact that we must have one `?`.

Furthermore, I noticed that in the `options.ts` file, there were interfaces with almost the same fields with only the optional flag or a few parameter changing. I put the interfaces in a `types.ts` file to split the implementation from the type definition. I also switched the `interface` to `type` because in the context, they are only dumb objects without methods on them, and types are easier to compose with `&`. That eliminates a lot of repetition in the options names. It still seems readable to me but I might be biased having done that kind of tweaks a lot. If you preferred the previous way I can revert that change.

Edit:

I ended up the following options:
- `mustHaveBlankDayField` to force having at least one `?`.
- `useLastDayOfMonth` for `L` in days of month field.
- `useLastDayOfWeek` for `L` in days of week field.
- `useNearestWeekday` for `W` in days of month field.
- `useNthWeekdayOfMonth` for `#` in days of week field.

### CODE REVIEW

**Comment by GuillaumeRochat** [comment]
Turns out that `L` in the day of month and day of week does not mean the same thing and does not have the same syntax. More complicated than expected. Example of documentation with more details than AWS doc : http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html

So instead of `useLastDay`, I'd go with `useLastDayOfMonth` and `useLastDayOfWeek` but the last day of week means the last occurrence of a specific day, like the last Friday of the month.

**Comment by GuillaumeRochat** [comment]
I believe this is similar to what AWS is using internally so maybe using that implementation as a reference would help : https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/CronExpression.java

According to that code, we cannot have `L`, `W` or `#` with other values, so we can't do things like `15,L` for the 15th and the last. But we can do weird things like `L-3` to mean 3 days before last. And we can also do things like `LW` to mean last weekday of the month. I'll try something different considering what I just found out.

**Comment by Airfooox** [comment]
Havn't looked at it in detail, but looks really nice to far, I'm glad you're working on it.

Another thing to consider: we should check these wildcards like L, L-2 etc. for the limits. Like when someone restricts the the days of the month from 1 to 15 and someone uses L, it shouldn't let them do that.

If you already integrated that, just ignore that stuff above, haha.

**Comment by Airfooox** [comment]
Other thing: I'm using semantic release and it uses the titles of the commits to figure out the next version. Could you use that syntax:

feat:
fix:
chore:

etc?

**Comment by GuillaumeRochat** [comment]
> Another thing to consider: we should check these wildcards like L, L-2 etc. for the limits. Like when someone restricts the the days of the month from 1 to 15 and someone uses L, it shouldn't let them do that.

Yes, that is a scenario that must be handled.

I tried a first implementation of the L with my understanding of it but apparently I didn't interpret the documentation well enough first time around. So you can't really make `15,L` because that tooling won't accept it from what I saw in the parser. I'll get AWS configured today so I'll be able to test some syntax edge cases and adjust accordingly.

**Pull request merged**
